name: HTML/CSS Validation

on:
  push:
    branches: ["main"]

jobs:
  validation:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install html5validator
          npm install -g stylelint stylelint-config-standard

      - name: Validate HTML
        run: |
          html5validator --root . --skip-non-html

      - name: Validate CSS
        run: |
          find . -name "*.css" -exec stylelint {} \;
